### ISSUE TITLE
[vite] Internal server error

### ISSUE THREAD

**Issue by maxfusionphp** [manga-raiku/raiku-app#80]
PS E:\phpProjact\raiku-app-release> quasar dev

 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

 App • Running "@quasar/testing-e2e-cypress" Quasar App Extension...
 App • Running "@quasar/testing-unit-vitest" Quasar App Extension...

 » Reported at............ 08/11/2023 23:49:19
 » App dir................ E:\phpProjact\raiku-app-release
 » App URL................ http://192.168.1.2:9000/
                           http://localhost:9000/
                           http://192.168.144.1:9000/
 » Dev mode............... spa
 » Pkg quasar............. v2.13.0
 » Pkg @quasar/app-vite... v1.6.2
 » Browser target......... es2019|edge88|firefox78|chrome87|safari13.1

23:49:26 [vite] Internal server error: vite.createFilter is not a function
  Plugin: vite:vue
  File: E:/phpProjact/raiku-app-release/node_modules/vite/dist/client/client.mjs
      at ReactiveEffect.fn (E:\phpProjact\raiku-app-release\node_modules\@vitejs\plugin-vue\dist\index.cjs:2728:16)
      at ReactiveEffect.run (E:\phpProjact\raiku-app-release\node_modules\@vue\reactivity\dist\reactivity.cjs.js:182:19)
      at ComputedRefImpl.get value [as value] (E:\phpProjact\raiku-app-release\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1131:33)
      at TransformContext.transform (E:\phpProjact\raiku-app-release\node_modules\@vitejs\plugin-vue\dist\index.cjs:2837:19)
      at Object.transform (E:\phpProjact\raiku-app-release\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39317:53)
      at doTransform (E:\phpProjact\raiku-app-release\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50043:29)
23:49:26 [vite] Internal server error: filter.value is not a function
  Plugin: vite:vue
  File: E:/phpProjact/raiku-app-release/.quasar/client-entry.js
      at TransformContext.transform (E:\phpProjact\raiku-app-release\node_modules\@vitejs\plugin-vue\dist\index.cjs:2837:19)
      at Object.transform (E:\phpProjact\raiku-app-release\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39317:53)
      at doTransform (E:\phpProjact\raiku-app-release\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50043:29)

**Comment by tachibana-shin** [comment]
Which package manager are you using `npm` or `pnpm`? I use `pnpm` in this project

**Comment by maxfusionphp** [comment]
I use npm. I will try to use pnpm
