### ISSUE TITLE
[plugin:vite:import-analysis] Failed to resolve import "raiku-pgs/thread" from "src\stores\plugin.ts". Does the file exist?

### ISSUE THREAD

**Issue by maxfusionphp** [manga-raiku/raiku-app#83]
[plugin:vite:import-analysis] Failed to resolve import "raiku-pgs/thread" from "src\stores\plugin.ts". Does the file exist?
E:/phpProjact/raiku-app-release/src/stores/plugin.ts:3:51
1  |  import { defineStore } from "pinia";
2  |  import { createWorkerPlugin, execPackageMjs } from "raiku-pgs/thread";
   |                                                      ^
3  |  import semverGt from "semver/functions/gt";
4  |
    at formatError (E:\phpProjact\raiku-app-release\node_modules\.pnpm\vite@2.9.16_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39080:46)
    at TransformContext.error (E:\phpProjact\raiku-app-release\node_modules\.pnpm\vite@2.9.16_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39076:19)
    at normalizeUrl (E:\phpProjact\raiku-app-release\node_modules\.pnpm\vite@2.9.16_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:58360:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TransformContext.transform (E:\phpProjact\raiku-app-release\node_modules\.pnpm\vite@2.9.16_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:58509:57)
    at Object.transform (E:\phpProjact\raiku-app-release\node_modules\.pnpm\vite@2.9.16_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39317:30)
    at doTransform (E:\phpProjact\raiku-app-release\node_modules\.pnpm\vite@2.9.16_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50043:29
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

**Comment by tachibana-shin** [comment]
You need to run `pnpm setup` instead of `pnpm install` because the project needs a few self-compiled dependencies

If you use Windows you don't need to run it instead run
```bash
pnpm i
pnpm build:npm
```
